"""Initial migration

Revision ID: 7858ffd65072
Revises: 
Create Date: 2025-04-21 12:31:24.461723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7858ffd65072'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventlogs_id'), 'eventlogs', ['id'], unique=False)
    op.create_index(op.f('ix_eventlogs_name'), 'eventlogs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventlogs_name'), table_name='eventlogs')
    op.drop_index(op.f('ix_eventlogs_id'), table_name='eventlogs')
    op.drop_table('eventlogs')
    # ### end Alembic commands ###
